server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/MonolithicArchitectureDB
    username: postgres
    password: asdsaddas
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

myapplication:
  name: Monolithic Architecture
  description: "This is a description of the Monolithic Architecture"
  info: "This is a info of the monolithic architecture application"